In [54]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import random
import json
import pickle

In [31]:
def flatten_json(json_file_path):
    with open(json_file_path, 'r') as f:
        data = json.load(f)

    df_formatted = pd.json_normalize(data)
    return df_formatted

file_path = 'C:/Capstone/trav-capstone/server/python/spotify_formatted.json'
df_read = flatten_json(file_path)
display(df_read)

,Unnamed:0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,valence,tempo,duration,country,region,language,pivot,price,condition,popularity
0,25193,spotify:track:0vvuIsoJ101Hme1VIXBIEi,144,"Rusherking,Duki",2.0,Duki,spotify:artist:1bAftSH8umNcGZ0uyV7LMg,argentinehiphop,https://i.scdn.co/image/ab6761610000e5eb9b2ccf...,1,...,0.5579999999999999,99.97200000000001,194400.0,Argentina,SouthAmerica,Spanish,1,11.694527,2.016941,1.842286
1,3004,spotify:track:7MCFjPDImfjQv7GynHgVrR,190,NickiNicole,1.0,NickiNicole,spotify:artist:2UZIAOlrnyZmyzt1nuXr9y,trapargentino,https://i.scdn.co/image/ab6761610000e5ebc43398...,0,...,0.576,90.02,179967.0,Argentina,SouthAmerica,Spanish,0,26.568784,1.783971,3.478551
2,21752,spotify:track:4MzXwWMhyBbmu6hOcLVD49,49,"BadBunny,JhayCortez",2.0,BadBunny,spotify:artist:4q3ewBCX7sLwd24euuV69X,latin,https://i.scdn.co/image/ab6761610000e5eb8ee9a6...,1,...,0.145,109.928,205090.0,Argentina,SouthAmerica,Spanish,0,12.505174,3.333350,2.983396
3,22033,spotify:track:03LfOYi0icz4souspZVVhq,35,"Bizarrap,NickyJam",2.0,NickyJam,spotify:artist:1SupJlEpv7RS2tPNRaHViT,latin,https://i.scdn.co/image/ab6761610000e5eb4d248e...,1,...,0.818,89.90700000000002,158087.0,Argentina,SouthAmerica,Spanish,1,28.876434,1.239435,1.725992
4,15930,spotify:track:0JAZWvvqttGFm4UMDsPQXC,145,"Ozuna,Camilo",2.0,Camilo,spotify:artist:28gNT5KBp7IjEOQoevXf9N,colombianpop,https://i.scdn.co/image/ab6761610000e5eb539ee1...,1,...,0.72,166.039,224187.0,Argentina,SouthAmerica,Spanish,1,13.705108,1.698137,2.663778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35755,1770900,spotify:track:3wGx3gYPjECKZazGNuPEX2,2,"JukySan,REDT",1.0,JukySan,spotify:artist:51wGpVg4Z3lv1IjuZAQjXn,v-pop,https://i.scdn.co/image/ab6761610000e5eb3fb0af...,0,...,0.371,96.002,190000,Vietnam,Asia,Vietnamese,0,24.973704,1.600258,1.572115
35756,1780210,spotify:track:1AAGvzJRWMTKx7PNfeTvP4,103,"PhuongLy,TINLE",2.0,PhuongLy,spotify:artist:5Kh0ta0UY4uJ4g2CIdq9V9,v-pop,https://i.scdn.co/image/ab6761610000e5ebb5656a...,1,...,0.111,105.01,242857,Vietnam,Asia,Vietnamese,0,20.464241,1.386090,3.221026
35757,1776505,spotify:track:5Z9KJZvQzH6PFmb8SNkxuk,74,"LilNasX,JackHarlow",2.0,JackHarlow,spotify:artist:2LIk90788K0zvyj2JJVwkJ,deepundergroundhiphop,https://i.scdn.co/image/ab6761610000e5ebed3a04...,1,...,0.892,150.087,212353,Vietnam,Asia,Vietnamese,1,15.523963,3.429560,2.792526
35758,1779476,spotify:track:4TgxFMOn5yoESW6zCidCXL,166,"Jawsh685,JasonDerulo,BTS",3.0,Jawsh685,spotify:artist:56mfhUDKa1vec6rSLZV5Eg,nzpop,https://i.scdn.co/image/ab6761610000e5eb011dde...,1,...,0.658,149.836,184905,Vietnam,Asia,Vietnamese,0,8.115735,3.601608,2.739911
35759,369228,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,valence,tempo,duration,country,region,language,pivot,11.861167,4.413960,2.386074

In [32]:
#df2 = df_read.select_dtypes(exclude=['object'])
dfSmall = df_read.groupby('country').apply(lambda x: x.sample(frac=0.28)).reset_index(drop=True)
display(dfSmall)

C:\Users\wasadmin\AppData\Local\Temp\2\ipykernel_6860\2211230018.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  dfSmall = df_read.groupby('country').apply(lambda x: x.sample(frac=0.28)).reset_index(drop=True)

,Unnamed:0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,valence,tempo,duration,country,region,language,pivot,price,condition,popularity
0,19221,spotify:track:52Fw40zkJt0rFW5qkB2uJt,165,"DJTao,Ecko",2.0,Ecko,spotify:artist:2Jb9jVnCpWkXtoGznFJ6bF,argentinehiphop,https://i.scdn.co/image/ab6761610000e5ebd84d83...,1,...,0.499,88.015,148544.0,Argentina,SouthAmerica,Spanish,1,5.419915,1.427425,3.502103
1,28713,spotify:track:5W1qmxHrMlQGGAiFA3ZQqP,75,"DímeloFlow,Dalex,Sech,JustinQuiles,Arcangel,De...",7.0,LennyTavárez,spotify:artist:1pQWsZQehhS4wavwh7Fnxd,traplatino,https://i.scdn.co/image/ab6761610000e5eb3da6d5...,1,...,0.609,83.99700000000001,277693.0,Argentina,SouthAmerica,Spanish,1,4.230417,1.918113,1.699658
2,5529,spotify:track:6c32C8T3KlXrbvWSoD5aON,174,MykeTowers,1.0,MykeTowers,spotify:artist:7iK8PXO48WeuP03g8YR51W,latin,https://i.scdn.co/image/ab6761610000e5eb9b7677...,0,...,0.682,110.042,222728.0,Argentina,SouthAmerica,Spanish,0,29.781371,3.427349,4.651420
3,16836,spotify:track:57Ba26w9eoXx8BBUNgRNLV,191,"SuperYei,JoneQuest,Sammy,MykeTowers,LennyTavár...",6.0,LennyTavárez,spotify:artist:1pQWsZQehhS4wavwh7Fnxd,latin,https://i.scdn.co/image/ab6761610000e5eb3da6d5...,1,...,0.569,189.984,307435.0,Argentina,SouthAmerica,Spanish,1,25.709970,4.555793,4.591942
4,4332,spotify:track:1yc7ERfIzFxPP1E0OFRvp0,51,CNCO,1.0,CNCO,spotify:artist:0eecdvMrqBftK0M1VKhaF4,latinpop,https://i.scdn.co/image/ab6761610000e5ebae9279...,0,...,0.53,172.003,176298.0,Argentina,SouthAmerica,Spanish,0,15.600053,2.162755,1.703619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10011,1772139,spotify:track:3wKCldl6riuEKxXlvuxFJ2,149,BLACKPINK,1.0,BLACKPINK,spotify:artist:41MozSoPIsD1dJM0CLPjZF,k-pop,https://i.scdn.co/image/ab6761610000e5eb9f7319...,0,...,0.315,151.954,199120,Vietnam,Asia,Vietnamese,0,15.354935,1.996468,2.918372
10012,1773200,spotify:track:50nfwKoDiSYg8zOCREWAm5,47,EdSheeran,1.0,EdSheeran,spotify:artist:6eUKZXaKkcviH0Ku9w2n3V,ukpop,https://i.scdn.co/image/ab6761610000e5eb12a2ef...,0,...,0.822,141.02,207853,Vietnam,Asia,Vietnamese,0,9.468474,1.270800,4.458944
10013,1772698,spotify:track:3Vi5XqYrmQgOYBajMWSvCi,69,DojaCat,1.0,DojaCat,spotify:artist:5cj0lLjcoR7YOSnhnX0Po5,pop,https://i.scdn.co/image/ab6761610000e5eb727a2a...,0,...,0.194,130.041,210560,Vietnam,Asia,Vietnamese,0,27.022819,1.034247,2.757783
10014,1779779,spotify:track:2MjpqyEA73TzenhDmj0RFN,60,"HoangTon,LyHan",2.0,HoangTon,spotify:artist:6xRZoWlE9twEkMC5NW4Z9f,v-pop,https://i.scdn.co/image/ab6761610000e5ebc42e52...,1,...,0.703,100.0,177600,Vietnam,Asia,Vietnamese,0,19.309956,4.287309,2.620964
10015,1765143,spotify:track:2bgTY4UwhfBYhGT4HUYStN,5,BTS,1.0,BTS,spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX,k-pop,https://i.scdn.co/image/ab6761610000e5eb5704a6...,0,...,0.695,109.99700000000001,164442,Vietnam,Asia,Vietnamese,0,16.304776,4.831986,2.311398

In [48]:
#df_read = pd.read_json('spotify_formatted.json')
# List of columns to keep
'''
columns_to_keep = [
    "artist_genre","record_name","danceability", "energy", "key", "mode", "loudness", "speechiness",
    "acousticness", "instrumentalness", "liveness", "valence", "tempo",
    "duration", "country", "region", "language", "price", "condition", "popularity"
]
'''
columns_to_keep = [
    "danceability", "energy", "key", "mode", "loudness", "speechiness",
    "acousticness", "instrumentalness", "liveness", "valence", "tempo",
    "duration", "price", "condition", "popularity"
]
# Update the DataFrame to keep only the specified columns
df_filtered = dfSmall[columns_to_keep]
display(df_filtered)

,danceability,energy,key,mode,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,price,condition,popularity
0,0.852,0.625,2.0,1.0,-6.5120000000000005,0.095,0.10300000000000001,2.2800000000000002e-05,0.0965,0.499,88.015,148544.0,5.419915,1.427425,3.502103
1,0.562,0.755,7.0,0.0,-4.367,0.11199999999999999,0.0967,2.25e-05,0.14300000000000002,0.609,83.99700000000001,277693.0,4.230417,1.918113,1.699658
2,0.805,0.806,6.0,0.0,-3.589,0.0393,0.0828,0.0,0.156,0.682,110.042,222728.0,29.781371,3.427349,4.651420
3,0.6559999999999999,0.665,1.0,1.0,-1.3869999999999998,0.18899999999999997,0.149,8.33e-06,0.16,0.569,189.984,307435.0,25.709970,4.555793,4.591942
4,0.656,0.705,5.0,0.0,-4.262,0.0908,0.166,0.0,0.202,0.53,172.003,176298.0,15.600053,2.162755,1.703619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10011,0.721,0.568,9,0,-7.264,0.0412,0.0108,0.000058,0.109,0.315,151.954,199120,15.354935,1.996468,2.918372
10012,0.788,0.859,2,1,-2.724,0.0856,0.281,0.0,0.0424,0.822,141.02,207853,9.468474,1.270800,4.458944
10013,0.664,0.609,1,1,-6.509,0.0707,0.304,0.0,0.0926,0.194,130.041,210560,27.022819,1.034247,2.757783
10014,0.803,0.55,2,0,-5.41,0.031,0.702,0.0,0.112,0.703,100.0,177600,19.309956,4.287309,2.620964
10015,0.759,0.45899999999999996,8,1,-5.187,0.0948,0.00323,0.0,0.0906,0.695,109.99700000000001,164442,16.304776,4.831986,2.311398

In [55]:
# Convert categorical 'genre' to numeric using one-hot encoding
df_filtered['price'] = pd.cut(df_filtered['price'], bins=5, labels=False)

# Remove columns with string data types
df_numeric = df_filtered.select_dtypes(exclude=['object'])

# Optimize data types
dfTemp = df_filtered.astype('float32')
df = dfTemp.dropna()
#df = df2.select_dtypes(exclude=['object'])
X = pd.get_dummies(df, columns=['price'])

# Check for non-numeric columns and convert them if necessary
# Assuming 'record_name' is the only non-numeric column you want to drop
#X = df_encoded.drop(columns=['uri','artist_id','artist_image'])

# Ensure all columns in X are numeric
# If there are other non-numeric columns, handle them here

# Train the NearestNeighbors model
knn = NearestNeighbors(n_neighbors=3, algorithm='auto').fit(X)

#add pickle file for model
with open('knn_model_spotify.pkl', 'wb') as file:
    pickle.dump(knn, file)

# Select a random product index
selected_product_index = random.randint(0, len(df) - 1)

# Get the features of the selected product
selected_product_features = X.iloc[selected_product_index].values.reshape(1, -1)

# Find the nearest neighbors
distances, indices = knn.kneighbors(selected_product_features)
recommended_product_indices = indices.flatten()
recommended_products = df.iloc[recommended_product_indices]

print("Selected Product:")
print(df.iloc[selected_product_index])
print("\nRecommended Products:")
print(recommended_products)

Selected Product:
danceability             0.829000
energy                   0.788000
key                      1.000000
mode                     1.000000
loudness                -5.276000
speechiness              0.080700
acousticness             0.051000
instrumentalness         0.000000
liveness                 0.065600
valence                  0.398000
tempo                  101.950996
duration            202353.000000
price                    3.000000
condition                3.625493
popularity               1.152924
Name: 3831, dtype: float32

Recommended Products:
      danceability  energy  key  mode  loudness  speechiness  acousticness  \
3831         0.829   0.788  1.0   1.0    -5.276       0.0807         0.051
3851         0.829   0.788  1.0   1.0    -5.276       0.0807         0.051
3875         0.829   0.788  1.0   1.0    -5.276       0.0807         0.051

      instrumentalness  liveness  valence       tempo  duration  price  \
3831               0.0    0.0656    0.398  101.950996  202353.0    3.0
3851               0.0    0.0656    0.398  101.950996  202353.0    2.0
3875               0.0    0.0656    0.398  101.950996  202353.0    3.0

      condition  popularity
3831   3.625493    1.152924
3851   2.288554    2.400983
3875   2.260089    4.970095

C:\Users\wasadmin\AppData\Local\Temp\2\ipykernel_6860\2779033425.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['price'] = pd.cut(df_filtered['price'], bins=5, labels=False)
C:\Users\wasadmin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

In [56]:
print(type(knn))

<class 'sklearn.neighbors._unsupervised.NearestNeighbors'>