In [19]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
import random
from wonderwords import RandomWord
from datetime import datetime, timedelta
from sklearn.preprocessing import LabelEncoder

file_path = 'C:/spotify_data/final.csv'  
df = pd.read_csv(file_path)
df['price'] = np.random.uniform(3.99, 30.99, size=len(df))
display(df)

C:\Users\wasadmin\AppData\Local\Temp\2\ipykernel_740\4189189104.py:10: DtypeWarning: Columns (2,4,9,12,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,31,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,Unnamed: 0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,instrumentalness,liveness,valence,tempo,duration,country,region,language,pivot,price
0,0,spotify:track:2gpQi3hbcUAcEG8m2dlgfB,1,Paulo Londra,1.0,Paulo Londra,spotify:artist:3vQ0GE3mI0dAaxIMYe5g7z,argentine hip hop,https://i.scdn.co/image/ab6761610000e5ebf796a9...,0,...,0.0,0.0658,0.557,173.935,178203.0,Argentina,South America,Spanish,0,14.742617
1,1,spotify:track:2x8oBuYaObjqHqgGuIUZ0b,2,WOS,1.0,WOS,spotify:artist:5YCc6xS5Gpj3EkaYGdjyNK,argentine indie,https://i.scdn.co/image/ab6761610000e5eb75e151...,0,...,0.0,0.134,0.262,81.956,183547.0,Argentina,South America,Spanish,0,22.165123
2,2,spotify:track:2SJZdZ5DLtlRosJ2xHJJJa,3,Paulo Londra,1.0,Paulo Londra,spotify:artist:3vQ0GE3mI0dAaxIMYe5g7z,argentine hip hop,https://i.scdn.co/image/ab6761610000e5ebf796a9...,0,...,0.0,0.0929,0.216,137.915,204003.0,Argentina,South America,Spanish,0,29.168765
3,3,spotify:track:1O2pcBJGej0pmH2Y9XZMs6,5,Cris Mj,1.0,Cris Mj,spotify:artist:1Yj5Xey7kTwvZla8sqdsdE,urbano chileno,https://i.scdn.co/image/ab6761610000e5eb8f4ebc...,0,...,0.000046,0.0534,0.832,96.018,153750.0,Argentina,South America,Spanish,0,16.640459
4,4,spotify:track:1TpZKxGnHp37ohJRszTSiq,6,Emilia,1.0,Emilia,spotify:artist:0AqlFI0tz2DsEoJlKSIiT9,pop argentino,https://i.scdn.co/image/ab6761610000e5ebaf96d1...,0,...,0.000063,0.101,0.501,95.066,133895.0,Argentina,South America,Spanish,0,25.700275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1787994,1787994,spotify:track:1XGmzt0PVuFgQYYnV2It7A,197,"Maroon 5, Wiz Khalifa",2.0,Maroon 5,spotify:artist:04gDigrS5kc9YWfZHwBETP,pop,https://i.scdn.co/image/ab6761610000e5eb288ac0...,1,...,0.0,0.287,0.545,110.015,231173,Vietnam,Asia,Vietnamese,0,7.343339
1787995,1787995,spotify:track:1XGmzt0PVuFgQYYnV2It7A,197,"Maroon 5, Wiz Khalifa",2.0,Wiz Khalifa,spotify:artist:137W8MRPWKqSmrBGDBFSop,hip hop,https://i.scdn.co/image/ab6761610000e5eb4bdf6d...,1,...,0.0,0.287,0.545,110.015,231173,Vietnam,Asia,Vietnamese,1,24.945954
1787996,1787996,spotify:track:6JIC3hbC28JZKZ8AlAqX8h,199,"Elton John, Dua Lipa, PNAU",3.0,Elton John,spotify:artist:3PhoLpVuITZKcymswpck5b,mellow gold,https://i.scdn.co/image/ab6761610000e5eb0a7388...,1,...,0.000073,0.0915,0.934,116.032,202735,Vietnam,Asia,Vietnamese,0,20.303611
1787997,1787997,spotify:track:6JIC3hbC28JZKZ8AlAqX8h,199,"Elton John, Dua Lipa, PNAU",3.0,Dua Lipa,spotify:artist:6M2wZ9GZgrQXHCFfjv46we,pop,https://i.scdn.co/image/ab6761610000e5ebd42a27...,1,...,0.000073,0.0915,0.934,116.032,202735,Vietnam,Asia,Vietnamese,1,13.503610
1787998,1787998,spotify:track:6JIC3hbC28JZKZ8AlAqX8h,199,"Elton John, Dua Lipa, PNAU",3.0,PNAU,spotify:artist:6n28c9qs9hNGriNa72b26u,alternative dance,https://i.scdn.co/image/ab6761610000e5eb999ea1...,1,...,0.000073,0.0915,0.934,116.032,202735,Vietnam,Asia,Vietnamese,1,25.443252

In [ ]:
def random_date(start_year=1975, end_year=2024):
    start_date = datetime(start_year, 1, 1)
    end_date = datetime(end_year, 12, 31)
    random_days = random.randint(0, (end_date - start_date).days)
    return (start_date + timedelta(days=random_days)).strftime('%m/%d/%Y')

# Fill null values in 'release_date' with random dates
df['release_date'] = df['release_date'].apply(lambda x: random_date() if pd.isnull(x) else x)
#display(df['release_date'])

0          2022-03-23
1          2022-04-06
2          2022-04-06
3          2022-01-21
4          2022-03-24
              ...
1787994    2012-01-01
1787995    2012-01-01
1787996    2021-10-22
1787997    2021-10-22
1787998    2021-10-22
Name: release_date, Length: 1787999, dtype: object

In [14]:
# Delete the 'week' column
#df = df.drop(columns=['week'])

# Sample 25% of the data based on the 'country' row
df_sampled = df.groupby('country').apply(lambda x: x.sample(frac=0.02)).reset_index(drop=True)

# Display the sampled DataFrame
display(df_sampled)

C:\Users\wasadmin\AppData\Local\Temp\2\ipykernel_740\2892840629.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_sampled = df.groupby('country').apply(lambda x: x.sample(frac=0.02)).reset_index(drop=True)

,Unnamed: 0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,instrumentalness,liveness,valence,tempo,duration,country,region,language,pivot,price
0,4911,spotify:track:6mm3K0yWp6uzfOMuipM9Zh,200,Piso 21,1.0,Piso 21,spotify:artist:4bw2Am3p9ji3mYsXNXtQcd,reggaeton,https://i.scdn.co/image/ab6761610000e5eb48ac6d...,0,...,0.00215,0.064,0.844,110.982,211998.0,Argentina,South America,Spanish,0,18.639220
1,13307,spotify:track:6w8yBI2vthyN9UnwO4UBWb,18,"Tiago PZK, LIT killah",2.0,LIT killah,spotify:artist:1vqR17Iv8VFdzure1TAXEq,trap triste,https://i.scdn.co/image/ab6761610000e5eb67d0ad...,1,...,0.000001,0.137,0.789,170.064,192353.0,Argentina,South America,Spanish,1,14.766788
2,23736,spotify:track:0kRJ3rwE3rTDJGnGO4HmoD,188,"El Jordan 23, Standly",2.0,El Jordan 23,spotify:artist:1fIJZfSmqQkuqfKNRmrS1V,mambo chileno,https://i.scdn.co/image/ab6761610000e5eb84265e...,1,...,0.0,0.0937,0.565,95.041,224842.0,Argentina,South America,Spanish,0,23.995609
3,23585,spotify:track:1p22yVi9e8DT6BEUvOZ0TL,75,"Emilia, Rusherking",2.0,Rusherking,spotify:artist:3Apb2lGmGJaBmr0TTBJvIZ,trap argentino,https://i.scdn.co/image/ab6761610000e5eb239e70...,1,...,0.0,0.111,0.574,94.946,164289.0,Argentina,South America,Spanish,1,27.008308
4,18200,spotify:track:5W1qmxHrMlQGGAiFA3ZQqP,86,"Dímelo Flow, Dalex, Sech, Justin Quiles, Arcan...",7.0,Sech,spotify:artist:77ziqFxp5gaInVrF2lj4ht,reggaeton,https://i.scdn.co/image/ab6761610000e5eb2f3649...,1,...,2.25e-05,0.14300000000000002,0.609,83.99700000000001,277693.0,Argentina,South America,Spanish,1,14.180730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35755,1765887,spotify:track:2EMbVMhUtYNfuAhTi9HvBk,27,"Changg, Lemese",1.0,Lemese,spotify:artist:0DL9VpY3UsZWQyDOO5Ej2o,v-pop,https://i.scdn.co/image/ab6761610000e5ebd947c2...,0,...,4.01e-06,0.0925,0.47,144.94799999999995,214948,Vietnam,Asia,Vietnamese,0,6.568867
35756,1773580,spotify:track:6lmJXxTcLTe6bdgwSfTqhO,100,WEAN,1.0,WEAN,spotify:artist:30eFAXoU2kTjJPf2cq80B8,vietnamese melodic rap,https://i.scdn.co/image/ab6761610000e5eb43e6a5...,0,...,0.0,0.135,0.528,110.648,210639,Vietnam,Asia,Vietnamese,0,15.856907
35757,1778536,spotify:track:6iWPQ9xAYH3ZePu2Z209Y6,52,"Tăng Phúc, Truong Thao Nhi",2.0,Truong Thao Nhi,spotify:artist:0MSThXXAv51swAKUOuZg8A,0,https://i.scdn.co/image/ab67616d0000b273e2a526...,1,...,0.0,0.11,0.383,127.238,226000,Vietnam,Asia,Vietnamese,1,24.865630
35758,1782633,spotify:track:4jPy3l0RUwlUI9T5XHBW2m,124,"24kGoldn, iann dior",2.0,24kGoldn,spotify:artist:6fWVd57NKTalqvmjRd2t8Z,cali rap,https://i.scdn.co/image/ab6761610000e5ebe32a61...,1,...,0.0,0.324,0.732,91.007,140533,Vietnam,Asia,Vietnamese,0,30.868608
35759,1388802,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,instrumentalness,liveness,valence,tempo,duration,country,region,language,pivot,16.241045

In [16]:
df_sampled = df_sampled.rename(columns={'track_name': 'record_name'})

In [21]:


#df_encoded = pd.get_dummies(df_sampled, columns=['artist_genre', 'price', 'language', 'danceability', 'energy', 'loudness', 'acousticness', 'liveness', 'valence', 'tempo', 'duration'])
column_encode=['artist_genre', 'price', 'language', 'danceability', 'energy', 'loudness', 'acousticness', 'liveness', 'valence', 'tempo', 'duration']
label_encoders = {}
for column_encode in df_sampled.columns:
    if df_sampled[column_encode].dtype == 'object':
        label_encoders[column_encode] = LabelEncoder()
        df_sampled[column_encode] = label_encoders[column_encode].fit_transform(df_sampled[column_encode])

# # Prepare the feature set
X = df_sampled.drop(columns=['record_name'])

# # Train the NearestNeighbors model
knn = NearestNeighbors(n_neighbors=3, algorithm='auto').fit(X)

# # Select a random product index
selected_product_index = random.randint(0, len(df_sampled) - 1)

# # Get the features of the selected product
selected_product_features = X.iloc[selected_product_index].values.reshape(1, -1)

# # Find the nearest neighbors
distances, indices = knn.kneighbors(selected_product_features)
recommended_product_indices = indices.flatten()
recommended_products = df.iloc[recommended_product_indices]

print("Selected Product:")
print(df.iloc[selected_product_index])
print("\nRecommended Products:")
print(recommended_products)

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']