In [1]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import random
import json
import pickle

In [2]:
def flatten_json(json_file_path):
    with open(json_file_path, 'r') as f:
        data = json.load(f)

    df_formatted = pd.json_normalize(data)
    return df_formatted

file_path = 'C:/Capstone/trav-capstone/server/python/spotify_formatted.json'
df_read = flatten_json(file_path)
display(df_read)
dfSmall = df_read.groupby('country').apply(lambda x: x.sample(frac=0.28)).reset_index(drop=True)
display(dfSmall)

,Unnamed:0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,valence,tempo,duration,country,region,language,pivot,price,condition,popularity
0,25193,spotify:track:0vvuIsoJ101Hme1VIXBIEi,144,"Rusherking,Duki",2.0,Duki,spotify:artist:1bAftSH8umNcGZ0uyV7LMg,argentinehiphop,https://i.scdn.co/image/ab6761610000e5eb9b2ccf...,1,...,0.5579999999999999,99.97200000000001,194400.0,Argentina,SouthAmerica,Spanish,1,11.694527,2.016941,1.842286
1,3004,spotify:track:7MCFjPDImfjQv7GynHgVrR,190,NickiNicole,1.0,NickiNicole,spotify:artist:2UZIAOlrnyZmyzt1nuXr9y,trapargentino,https://i.scdn.co/image/ab6761610000e5ebc43398...,0,...,0.576,90.02,179967.0,Argentina,SouthAmerica,Spanish,0,26.568784,1.783971,3.478551
2,21752,spotify:track:4MzXwWMhyBbmu6hOcLVD49,49,"BadBunny,JhayCortez",2.0,BadBunny,spotify:artist:4q3ewBCX7sLwd24euuV69X,latin,https://i.scdn.co/image/ab6761610000e5eb8ee9a6...,1,...,0.145,109.928,205090.0,Argentina,SouthAmerica,Spanish,0,12.505174,3.333350,2.983396
3,22033,spotify:track:03LfOYi0icz4souspZVVhq,35,"Bizarrap,NickyJam",2.0,NickyJam,spotify:artist:1SupJlEpv7RS2tPNRaHViT,latin,https://i.scdn.co/image/ab6761610000e5eb4d248e...,1,...,0.818,89.90700000000002,158087.0,Argentina,SouthAmerica,Spanish,1,28.876434,1.239435,1.725992
4,15930,spotify:track:0JAZWvvqttGFm4UMDsPQXC,145,"Ozuna,Camilo",2.0,Camilo,spotify:artist:28gNT5KBp7IjEOQoevXf9N,colombianpop,https://i.scdn.co/image/ab6761610000e5eb539ee1...,1,...,0.72,166.039,224187.0,Argentina,SouthAmerica,Spanish,1,13.705108,1.698137,2.663778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35755,1770900,spotify:track:3wGx3gYPjECKZazGNuPEX2,2,"JukySan,REDT",1.0,JukySan,spotify:artist:51wGpVg4Z3lv1IjuZAQjXn,v-pop,https://i.scdn.co/image/ab6761610000e5eb3fb0af...,0,...,0.371,96.002,190000,Vietnam,Asia,Vietnamese,0,24.973704,1.600258,1.572115
35756,1780210,spotify:track:1AAGvzJRWMTKx7PNfeTvP4,103,"PhuongLy,TINLE",2.0,PhuongLy,spotify:artist:5Kh0ta0UY4uJ4g2CIdq9V9,v-pop,https://i.scdn.co/image/ab6761610000e5ebb5656a...,1,...,0.111,105.01,242857,Vietnam,Asia,Vietnamese,0,20.464241,1.386090,3.221026
35757,1776505,spotify:track:5Z9KJZvQzH6PFmb8SNkxuk,74,"LilNasX,JackHarlow",2.0,JackHarlow,spotify:artist:2LIk90788K0zvyj2JJVwkJ,deepundergroundhiphop,https://i.scdn.co/image/ab6761610000e5ebed3a04...,1,...,0.892,150.087,212353,Vietnam,Asia,Vietnamese,1,15.523963,3.429560,2.792526
35758,1779476,spotify:track:4TgxFMOn5yoESW6zCidCXL,166,"Jawsh685,JasonDerulo,BTS",3.0,Jawsh685,spotify:artist:56mfhUDKa1vec6rSLZV5Eg,nzpop,https://i.scdn.co/image/ab6761610000e5eb011dde...,1,...,0.658,149.836,184905,Vietnam,Asia,Vietnamese,0,8.115735,3.601608,2.739911
35759,369228,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,valence,tempo,duration,country,region,language,pivot,11.861167,4.413960,2.386074

C:\Users\wasadmin\AppData\Local\Temp\2\ipykernel_5760\3472255497.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  dfSmall = df_read.groupby('country').apply(lambda x: x.sample(frac=0.28)).reset_index(drop=True)

,Unnamed:0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,valence,tempo,duration,country,region,language,pivot,price,condition,popularity
0,4703,spotify:track:5uHAzGa4d9j35DEbhUwGhi,163,WOS,1.0,WOS,spotify:artist:5YCc6xS5Gpj3EkaYGdjyNK,trapargentino,https://i.scdn.co/image/ab6761610000e5eb75e151...,0,...,0.353,140.04,176395.0,Argentina,SouthAmerica,Spanish,0,25.932193,3.528172,1.142664
1,24745,spotify:track:41tkGjGDeoInSqQTFTPluG,67,"Duki,Lara91k",2.0,Duki,spotify:artist:1bAftSH8umNcGZ0uyV7LMg,traptriste,https://i.scdn.co/image/ab6761610000e5eb9b2ccf...,1,...,0.23199999999999998,81.95,244783.0,Argentina,SouthAmerica,Spanish,0,23.460569,3.741370,1.561503
2,7010,spotify:track:0Bv7O6fmZk3GrNQFYJaXPn,17,"LaPantera,Quevedo,Juseph,AbhirHathi,Bejo,CruzC...",7.0,Quevedo,spotify:artist:52iwsT98xCoGgiGntTiR7K,traplatino,https://i.scdn.co/image/ab6761610000e5ebb27545...,1,...,0.739,173.974,413111.0,Argentina,SouthAmerica,Spanish,1,5.185392,4.831888,3.575808
3,11449,spotify:track:6GsD646HrIDJJpzoY9T1Rt,8,"Duki,JustinQuiles,Bizarrap",3.0,Bizarrap,spotify:artist:716NhGYqD1jl2wI1Qkgq36,popvenezolano,https://i.scdn.co/image/ab6761610000e5eb12085f...,1,...,0.713,92.019,196727.0,Argentina,SouthAmerica,Spanish,1,6.000969,1.439985,4.572383
4,3310,spotify:track:4jLuoxmW7sA4MA3AaVVpNO,119,Miranda!,1.0,Miranda!,spotify:artist:2eEmsgWmUFMbtU7agJpnjY,latinpop,https://i.scdn.co/image/ab6761610000e5eb9c7c6d...,0,...,0.953,119.984,183960.0,Argentina,SouthAmerica,Spanish,0,12.904428,3.354799,3.607466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10011,1776334,spotify:track:5xOkL4eAs735nm6mcnvfS6,100,"FloD,GiangNguyễn",2.0,GiangNguyễn,spotify:artist:0aDZC2CPSqgpZwzqrh0DeF,0,https://i.scdn.co/image/ab67616d0000b2737f5cf8...,1,...,0.713,117.952,159974,Vietnam,Asia,Vietnamese,1,14.071819,3.812585,2.041601
10012,1768650,spotify:track:0QzuaeCEEOV40Pn7IvKEny,30,dhruv,1.0,dhruv,spotify:artist:70NcAr4ZtA3FAqU16iQZSb,nycpop,https://i.scdn.co/image/ab6761610000e5eb9d9fb4...,0,...,0.196,109.23899999999999,171743,Vietnam,Asia,Vietnamese,0,23.824803,4.561100,4.788097
10013,1771394,spotify:track:5eXBXreN3d1zdj6Sa8dS0u,3,BTS,1.0,BTS,spotify:artist:3Nrfpe0tUJi4K4DXYWgMUX,k-pop,https://i.scdn.co/image/ab6761610000e5eb5704a6...,0,...,0.646,124.925,187585,Vietnam,Asia,Vietnamese,0,20.164002,4.484026,2.113218
10014,1786092,spotify:track:3ESeHjnPRxAg4mW3KsFyXi,153,"Đen,ThànhĐồng",2.0,Đen,spotify:artist:1LEtM3AleYg1xabW6CRkpi,indieviet,https://i.scdn.co/image/ab6761610000e5eb37206c...,1,...,0.52,78.977,264000,Vietnam,Asia,Vietnamese,0,23.007363,2.601248,1.102023
10015,1775207,spotify:track:6dkCXQoMZoEonJbbFYH83r,109,"K-ICM,VickyNhung",2.0,K-ICM,spotify:artist:6mD6SQbvl9pILx7SAHBzbq,v-pop,https://i.scdn.co/image/ab6761610000e5eb452319...,1,...,0.738,110.024,236247,Vietnam,Asia,Vietnamese,0,24.907064,4.635199,3.679090

In [ ]:
dfSmall = df_read.groupby('country').apply(lambda x: x.sample(frac=0.28)).reset_index(drop=True)
display(dfSmall)

In [ ]:

columns_to_keep = [
    "danceability", "energy", "key", "mode", "loudness", "speechiness",
    "acousticness", "instrumentalness", "liveness", "valence", "tempo",
    "duration", "price", "condition", "popularity"
]
df_filtered = dfSmall[columns_to_keep]
display(df_filtered)

In [ ]:
# Convert categorical 'genre' to numeric using one-hot encoding
df_filtered['price'] = pd.cut(df_filtered['price'], bins=5, labels=False)

# Remove columns with string data types
df_numeric = df_filtered.select_dtypes(exclude=['object'])

# Optimize data types
dfTemp = df_filtered.astype('float32')
df = dfTemp.dropna()
X = pd.get_dummies(df, columns=['price'])

# Check for non-numeric columns and convert them if necessary
# Train the NearestNeighbors model
knn = NearestNeighbors(n_neighbors=3, algorithm='auto').fit(X)

#add pickle file for model
with open('knn_model_spotify.pkl', 'wb') as file:
    pickle.dump(knn, file)

# Select a random product index
selected_product_index = random.randint(0, len(df) - 1)

# Get the features of the selected product
selected_product_features = X.iloc[selected_product_index].values.reshape(1, -1)

# Find the nearest neighbors
distances, indices = knn.kneighbors(selected_product_features)
recommended_product_indices = indices.flatten()
recommended_products = df.iloc[recommended_product_indices]

print("Selected Product:")
print(df.iloc[selected_product_index])
print("\nRecommended Products:")
print(recommended_products)

In [ ]:
print(type(knn))